FROM lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0

COPY csc_sim/atdome-setup.sh /home/saluser/atdome-setup.sh
COPY csc_sim/atdome.py /home/saluser/atdome.py
COPY config /home/saluser/config

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/atdome-setup.sh"]
