FROM lsstts/develop-env:sal_v4.0.0_salobj_v5.0.0

COPY csc_sim/testcsc-setup.sh /home/saluser/testcsc-setup.sh
COPY csc_sim/testcsc.py /home/saluser/testcsc.py
COPY config /home/saluser/config
WORKDIR /home/saluser
ENTRYPOINT ["/home/saluser/testcsc-setup.sh"]
