ARG LSSTTS_DEV_VERSION=develop
FROM lsstts/develop-env:${LSSTTS_DEV_VERSION}

COPY csc_sim/testcsc-setup.sh /home/saluser/testcsc-setup.sh
COPY csc_sim/testcsc.py /home/saluser/testcsc.py
COPY config /home/saluser/config
WORKDIR /home/saluser
ENTRYPOINT ["/home/saluser/testcsc-setup.sh"]
