FROM lsstts/develop-env:c0010

COPY csc_sim/watcher-setup.sh /home/saluser/watcher-setup.sh
COPY config /home/saluser/config

RUN source /opt/lsst/software/stack/loadLSST.bash \
    && source /home/saluser/.setup_salobj.sh \
    && setup ts_sal -t current \
    && /home/saluser/repos/ts_sal/bin/make_idl_files.py Watcher

RUN git clone --depth 1 https://github.com/lsst-ts/ts_watcher.git  /home/saluser/repos/ts_watcher

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/watcher-setup.sh"]
