FROM lsstts/develop-env:c0010

COPY weatherstation_setup.sh /home/saluser/setup.sh
COPY csc_sim/weatherstation-setup.sh /home/saluser/weatherstation-setup.sh
COPY csc_sim/weatherstation.py /home/saluser/weatherstation.py
COPY config /home/saluser/config

RUN git clone --depth 1 https://github.com/lsst-ts/ts_weatherstation.git  /home/saluser/repos/ts_weatherstation

RUN source /home/saluser/setup.sh

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/weatherstation-setup.sh"]
