FROM lsstts/develop-env:20190705_sal3.10.0_salobj

COPY csc-sim/atdome-setup.sh /home/saluser/atdome-setup.sh
COPY config /home/saluser/config

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/atdome-setup.sh"]
