FROM lsstts/develop-env:c0010

COPY csc_sim/scriptqueue-setup.sh /home/saluser/scriptqueue-setup.sh
COPY csc_sim/scriptqueue.py /home/saluser/scriptqueue.py
COPY config /home/saluser/config
WORKDIR /home/saluser
ENTRYPOINT ["/home/saluser/scriptqueue-setup.sh"]
