FROM lsstts/develop-env:salobj4_b61

WORKDIR /usr/src/love
COPY simulator/requirements.txt .
RUN source /opt/lsst/software/stack/loadLSST.bash && pip install -r requirements.txt
COPY config ./config
COPY config /home/saluser/config

WORKDIR /home/saluser
CMD ["/usr/src/love/simulator/start-daemon.sh"]
