ARG LSSTTS_DEV_VERSION=develop
FROM lsstts/develop-env:${LSSTTS_DEV_VERSION}

COPY csc_sim/scriptqueue-setup.sh /home/saluser/scriptqueue-setup.sh
COPY csc_sim/scriptqueue.py /home/saluser/scriptqueue.py
COPY config /home/saluser/config
WORKDIR /home/saluser
ENTRYPOINT ["/home/saluser/scriptqueue-setup.sh"]
