ARG LSSTTS_DEV_VERSION=c0010
FROM lsstts/develop-env:${LSSTTS_DEV_VERSION}
WORKDIR /home/saluser/
COPY simulator/jupyter.sh /home/saluser/setup.sh
RUN source /opt/lsst/software/stack/loadLSST.bash \
    && source /home/saluser/.setup_salobj.sh \
    && setup ts_sal -t current \
    && /home/saluser/repos/ts_sal/bin/make_idl_files.py Watcher

RUN git clone --depth 1 https://github.com/lsst-ts/ts_watcher.git  /home/saluser/repos/ts_watcher


CMD ["/home/saluser/setup.sh"]