FROM lsstts/develop-env:salobj4_b61

COPY csc_sim/atdome-setup.sh /home/saluser/atdome-setup.sh
COPY csc_sim/atdome.py /home/saluser/atdome.py
COPY config /home/saluser/config

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/atdome-setup.sh"]
