FROM lsstts/develop-env:c0010

COPY environment_setup.sh /home/saluser/setup.sh
COPY csc_sim/environment-setup.sh /home/saluser/environment-setup.sh
COPY csc_sim/environment.py /home/saluser/environment.py
COPY config /home/saluser/config

RUN git clone --depth 1 https://github.com/lsst-ts/ts_environment.git  /home/saluser/repos/ts_environment

RUN source /home/saluser/setup.sh

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/environment-setup.sh"]
