version: "3.7"

services:
  simulator:
    container_name: love-simulator-mount
    build:
      context: ..
      dockerfile: docker/Dockerfile-dev
      args:
        dev_cycle: ${dev_cycle}
    image: love-simulator-mount-image
    environment:
      - LSST_DDS_PARTITION_PREFIX=local
    volumes:
      - ..:/usr/src/love
    command: "/usr/src/love/docker/setup-dev.sh"
    stdin_open: true
    tty: true
