ARG dev_cycle=develop
FROM lsstts/develop-env:${dev_cycle}

COPY csc_sim/atmcs-setup.sh /home/saluser/atmcs-setup.sh
COPY csc_sim/atmcs.py /home/saluser/atmcs.py
COPY config /home/saluser/config

ENTRYPOINT ["/bin/bash", "--"]
CMD ["/home/saluser/atmcs-setup.sh"]
