ARG dev_cycle=develop
FROM lsstts/develop-env:${dev_cycle}

COPY csc_sim/testcsc-setup.sh /home/saluser/testcsc-setup.sh
COPY csc_sim/testcsc.py /home/saluser/testcsc.py
COPY config /home/saluser/config
WORKDIR /home/saluser
ENTRYPOINT ["/home/saluser/testcsc-setup.sh"]
